### PR TITLE
feat: support redis path mode

### PR DESCRIPTION
**Pull request by qingdengyue**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change
support redis path mode .
https://github.com/luin/ioredis/blob/HEAD/API.md#Redis

### CODE REVIEW

**Comment by qingdengyue** [comment]
https://github.com/eggjs/egg/issues/4452

**Comment by KenyeeC** [comment]
@fengmk2 @atian25 大佬们看看这个 pr 能不能合一下，同样需要用 path 来连接

**Review by fengmk2 — APPROVED** [review]
+1

**Comment by fengmk2** [comment]
2.5.0

**Pull request merged**
